export const ROUTES = {
    HOME: '/',
    TOURS: '/tours',
    EXCURSION: '/excursion',
    TOUR_1: '/tours/1',
    TOUR_2: '/tours/2',
    TOUR_3: '/tours/3',
    TOUR_4: '/tours/4',
    TOUR_5: '/tours/5',
    TOUR_6: '/tours/6',
    TOUR_7: '/tours/7',
    TOUR_8: '/tours/8',
    TOUR_9: '/tours/9',
    EXCURSION_1: '/excursion/1',
    EXCURSION_2: '/excursion/2',
    EXCURSION_3: '/excursion/3',
    EXCURSION_4: '/excursion/4',
    EXCURSION_5: '/excursion/5',
    EXCURSION_6: '/excursion/6',
    ABOUT: '/about',
    CONTACT: '/contact',
};
